#!/bin/bash
set -e -E -u

SPRING_DIR=${1:-~/spring}
ERL_INTERFACE_DIR=${2:-/usr/lib/erlang/lib/erl_interface-*}
SCRIPT_DIR=$PWD

echo "Preparing NullErlangAI development environment"
echo " spring install: $SPRING_DIR"
echo "  erl interface: $ERL_INTERFACE_DIR"

git clean -fx

ln -sf $ERL_INTERFACE_DIR erl_interface

(
    cd ../../..
    cmake -DCMAKE_INSTALL_PREFIX=$SPRING_DIR -DAI_TYPES="NATIVE" .
    make install-spring
)

(
    cd $SPRING_DIR/share/games/spring
    ln -sf $SCRIPT_DIR/res/maps .
    ln -sf $SCRIPT_DIR/res/games .
)

make install
