#!/bin/bash
set -e -E -u

cd $(dirname $0)

# SPRING_DIR=/build/spring
SPRING_DIR=~/spring

# misc/generate-sources
make install

epmd -daemon
# $SPRING_DIR/bin/spring-headless -w res/nullai_test.txt
$SPRING_DIR/bin/spring -w res/nullai_test.txt
