#!/bin/bash
set -e -E -u

SPRING_DIR=${1:-~/spring}
ERL_INTERFACE_DIR=${2:-/usr/lib/erlang/lib/erl_interface-*}
SCRIPT_DIR=$PWD

echo "Preparing TccAI development environment"
echo " spring install: $SPRING_DIR"
echo "  erl interface: $ERL_INTERFACE_DIR"

git clean -fx

ln -sf $ERL_INTERFACE_DIR erl_interface

(
    cd ../../..
    cmake .
)

mkdir -p $SPRING_DIR/games $SPRING_DIR/maps

make install
